# google configuration
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=38163298190-a1m8306dniniaihlbnpe9ngshi2bqq0o.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# github configuration
spring.security.oauth2.client.registration.github.client-name=github
spring.security.oauth2.client.registration.github.client-id=Iv23liED01RzwbcWbLvt
spring.security.oauth2.client.registration.github.client-secret=258174f7f31bfff45989b63a872620fa607dc987
spring.security.oauth2.client.registration.github.scope=email,profile
# cloudinary configurations
cloudinary.api.key=739575454517612
cloudinary.api.secret=usOCQQnxBpPnlsn7-lk_VxI7BmU
cloudinary.cloud.name=dsu8ctndq
#Email configurations
# spring.mail.host=live.smtp.mailtrap.io
# spring.mail.port=587
# spring.mail.username=smtp@mailtrap.io
# spring.mail.password=284b3fd5d5a7801a2c42f644ca359fc0

# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# spring.mail.from=Linko@demomailtrap.co

# ===============================
# Gmail SMTP Configuration
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=satyamsharma061706@gmail.com
spring.mail.password=ebsjaimzsdtzgboi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.from=satyamsharma061706@gmail.com

# yeh he password=ebsj aimz sdtz gboi
# spring.mail.username=${GMAIL_APP_USERNAME}
# spring.mail.password=${GMAIL_APP_PASSWORD}
